# Generated by Django 5.1.6 on 2025-02-13 18:17

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DogProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('breed', models.CharField(choices=[('Africanis', 'Africanis'), ('German Shepherd', 'German Shepherd'), ('Labrador Retriever', 'Labrador Retriever'), ('Golden Retriever', 'Golden Retriever'), ('Bulldog', 'Bulldog'), ('Poodle', 'Poodle'), ('Other', 'Other (Specify)')], max_length=50)),
                ('custom_breed', models.CharField(blank=True, help_text="Specify if 'Other' is selected", max_length=100, null=True)),
                ('age', models.PositiveIntegerField()),
                ('medical_history', models.TextField(blank=True, help_text='Add any past medical history, allergies, or treatments.', null=True)),
                ('image', models.ImageField(default='dog_profiles/default.jpg', upload_to='dog_profiles/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
