# Generated by Django 5.1.6 on 2025-02-19 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vets', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={'ordering': ['-date']},
        ),
    ]
