# Generated by Django 5.1.6 on 2025-02-19 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vets', '0002_alter_appointment_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={},
        ),
    ]
