# Generated by Django 5.1.6 on 2025-02-19 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vets', '0003_alter_appointment_options'),
    ]

    operations = [
    ]
